# Generated by Django 5.2.12 on 2026-03-10 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('backend', models.CharField(default='postgres', max_length=50)),
                ('coordination', models.CharField(default='sequential', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('agent', models.CharField(default='custom', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_id', models.CharField(max_length=200, unique=True)),
                ('version', models.IntegerField()),
                ('agent', models.CharField(default='custom', max_length=100)),
                ('agent_version', models.CharField(blank=True, max_length=100)),
                ('tasks', models.JSONField(default=list)),
                ('decisions', models.JSONField(default=list)),
                ('open_questions', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('raw_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='projects.session')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='projects_pr_project_38fe3b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org'], name='projects_pr_org_id_376d00_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_id'], name='projects_se_session_22b68b_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['project'], name='projects_se_project_e01d76_idx'),
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['handoff_id'], name='projects_ha_handoff_6e5570_idx'),
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['session', '-version'], name='projects_ha_session_fb42e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='handoff',
            unique_together={('session', 'version')},
        ),
    ]
